version: '3.8'

volumes:
  postgres_data:
  folder_static:
  folder_media:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    build: .
    volumes:
      - folder_static:/code/static/
      - folder_media:/code/media/
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - "8005:8005"
  nginx:
    image: nginx:1.19.5
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - folder_static:/code/static/
      - folder_media:/code/media/
    ports:
      - "80:80"
    depends_on: 
      - web
